spring:
  profiles:
    active: ${spring.profile.active:master}
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
      - id: service_user
        uri: lb://service-user
        predicates:
        - Path=/user/**
        filters:
        - StripPrefix=1
      - id: service_company
        uri: lb://service-company
        predicates:
        - Path=/company/**
        filters:
        - StripPrefix=1
      loadbalancer:
        use404: true

server:
  port: 8080
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
